## Numpy


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

arr1 =np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 =np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [8]:
arr2=np.array([[1,2,3,4,5],[2,4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 4 5 6 7]]
(2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

print("arry:\n",arr)
print("shape:",arr.shape)
print("number of dimension:")
print("size (number of elements):",arr.ndim)
print("data type:",arr.dtype)
print("item size(in bytes):",arr.itemsize)


arry:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimension:
size (number of elements): 2
data type: int64
item size(in bytes): 8


In [23]:
### numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,5,6,8])
print(arr1-arr2)
print(arr1+arr2)
print(arr1*arr2)


[-1 -1 -2 -2 -3]
[ 3  5  8 10 13]
[ 2  6 15 24 40]


In [25]:
arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
## array slicing and indexing

arr=np.array([[1,2,3,4,],[5,6,7,8],[7,5,3,4]])
print("array : \n" ,arr)


array : 
 [[1 2 3 4]
 [5 6 7 8]
 [7 5 3 4]]


In [32]:
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,1:3])
print(arr[1:,2:])

1
[[3 4]
 [7 8]]
[[6 7]
 [5 3]]
[[7 8]
 [3 4]]


In [33]:
## modify

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  7   5   3   4]]


In [34]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [36]:
## normalization
## to have a mean of 0 and standard deviation

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev =np.std(data)


normalized_data =(data-mean)/std_dev
print("normalized data:" ,normalized_data)


normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [37]:
data = np.array([1,2,3,4,5,6,7,8,10])

mean=np.mean(data)
print("mean:" , mean)

std_dev=np.std(data)
print("std dev" , std_dev)

median =np.median(data)
print("median", median)

variance = np.var(data)
print("variance:" , variance)

mean: 5.111111111111111
std dev 2.7666443551086073
median 5.0
variance: 7.65432098765432


In [47]:
## logical opeerator

data =np.array([1,2,3,45,5,5,6,8,9])

data[(data>=6)& (data <=9)]

array([6, 8, 9])